version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/usage-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/usage-service/airflow"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
