"""create usage tables

Revision ID: 73ccf3578c56
Revises: 
Create Date: 2026-02-16 00:51:28.473346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73ccf3578c56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_aggregates',
    sa.Column('customer_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('daily_total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('monthly_total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('rolling_avg', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', 'metric')
    )
    op.create_table('usage_events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('invoice_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('embedding_processed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_events')
    op.drop_table('usage_aggregates')
    # ### end Alembic commands ###
