# Base Python image
FROM python:3.11-slim

# System dependencies for confluent_kafka
RUN apt-get update && apt-get install -y gcc librdkafka-dev git && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

COPY consumer/ consumer/
COPY models/ models/
COPY avro/ avro/
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1

# Command to run Kafka consumer
CMD ["python", "consumer/event_consume.py"]
